### ISSUE TITLE
Invalid CSS value

### ISSUE THREAD

**Issue by ftonato** [octacode/Octa-color-Gamey#2]
Hi @octacode,

I was looking at your code and i found [this small `typo`](https://github.com/octacode/Octa-color-Gamey/blob/master/colorgame.css#L43).

```css
#stripe{
	background: white;
	height: : 30px; /* Please, check out this line! */
	text-align: center;
}
```
